import fs from 'fs';
import path from 'path';
import { getDb } from '../db/index.js';

const FRP_CONFIG_PATH = process.env.FRP_CONFIG_PATH || '/app/frp/frps.toml';

export function updateFrpConfig() {
  try {
    const db = getDb();
    const ports = db.prepare(`
      SELECT p.port, p.protocol, u.email 
      FROM ports p 
      JOIN users u ON p.user_id = u.id 
      WHERE p.is_active = 1 AND u.is_active = 1
    `).all();

    const allowPorts = ports.map(p => p.port);
    
    const config = `
# FRP Server Configuration - Auto Generated
# Do not edit manually

bindPort = ${process.env.FRP_BIND_PORT || 7000}
auth.token = "${process.env.FRP_TOKEN || 'change-this-token'}"

webServer.addr = "0.0.0.0"
webServer.port = ${process.env.FRP_DASHBOARD_PORT || 7500}
webServer.user = "admin"
webServer.password = "${process.env.ADMIN_PASSWORD || 'admin123456'}"

log.to = "/app/frp/frps.log"
log.level = "info"
log.maxDays = 3

# Allowed ports
allowPorts = [
  { start = ${process.env.USER_PORT_MIN || 10000}, end = ${process.env.USER_PORT_MAX || 60000} }
]

# Transport settings
transport.maxPoolCount = 5
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.tcpKeepalive = 7200
`.trim();

    const configDir = path.dirname(FRP_CONFIG_PATH);
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }

    fs.writeFileSync(FRP_CONFIG_PATH, config);
    console.log('FRP配置已更新');

    // 尝试重载FRP (如果在Docker中运行)
    try {
      const { execSync } = require('child_process');
      execSync('pkill -HUP frps', { stdio: 'ignore' });
    } catch (e) {
      // 忽略错误，可能frps不在运行
    }
  } catch (err) {
    console.error('更新FRP配置失败:', err);
  }
}

export function generateClientConfig(userEmail, ports) {
  const serverAddr = process.env.SERVER_ADDR || 'your-server-ip';
  const serverPort = process.env.FRP_BIND_PORT || 7000;
  const token = process.env.FRP_TOKEN || 'change-this-token';

  let config = `
# FRP Client Configuration for ${userEmail}
# Generated by FRP Panel

serverAddr = "${serverAddr}"
serverPort = ${serverPort}
auth.token = "${token}"

log.to = "./frpc.log"
log.level = "info"
log.maxDays = 3
`;

  ports.forEach((p, i) => {
    config += `
[[proxies]]
name = "${userEmail.split('@')[0]}-${p.protocol}-${p.port}"
type = "${p.protocol}"
localIP = "127.0.0.1"
localPort = ${p.port}
remotePort = ${p.port}
`;
  });

  return config.trim();
}
