import fs from 'fs';
import path from 'path';
import { getDb, getSettings, getFrpToken } from '../db/index.js';

const FRP_CONFIG_PATH = process.env.FRP_CONFIG_PATH || '/app/frp/frps.toml';

export function updateFrpConfig() {
  try {
    const db = getDb();
    const ports = db.prepare(`
      SELECT p.port, p.protocol, p.local_ip, p.local_port, u.email, u.bandwidth_limit
      FROM ports p 
      JOIN users u ON p.user_id = u.id 
      WHERE p.is_active = 1 AND u.is_active = 1
    `).all();

    // FRP Dashboard 使用独立账号密码
    const dashboardUser = process.env.FRP_DASHBOARD_USER || 'admin';
    const dashboardPwd = process.env.FRP_DASHBOARD_PWD || 'frp123456';
    
    const config = `
# FRP Server Configuration - Auto Generated
# Do not edit manually

bindPort = ${process.env.FRP_BIND_PORT || 7000}
auth.token = "${process.env.FRP_TOKEN || 'change-this-token'}"

webServer.addr = "0.0.0.0"
webServer.port = ${process.env.FRP_DASHBOARD_PORT || 7500}
webServer.user = "${dashboardUser}"
webServer.password = "${dashboardPwd}"

log.to = "/app/frp/frps.log"
log.level = "info"
log.maxDays = 3

# Allowed ports
allowPorts = [
  { start = ${process.env.USER_PORT_MIN || 10000}, end = ${process.env.USER_PORT_MAX || 60000} }
]

# Transport settings
transport.maxPoolCount = 5
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 60
transport.tcpKeepalive = 7200
`.trim();

    const configDir = path.dirname(FRP_CONFIG_PATH);
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }

    fs.writeFileSync(FRP_CONFIG_PATH, config);
    console.log('FRP配置已更新');

    // 尝试重载FRP
    try {
      const { execSync } = require('child_process');
      execSync('pkill -HUP frps', { stdio: 'ignore' });
    } catch (e) {
      // 忽略错误
    }
  } catch (err) {
    console.error('更新FRP配置失败:', err);
  }
}

export function generateClientConfig(user, ports) {
  const settings = getSettings();
  const serverAddr = settings.server_ip || process.env.SERVER_IP || 'your-server-ip';
  const serverPort = process.env.FRP_BIND_PORT || 7000;
  const token = getFrpToken();
  const bandwidthLimit = user.bandwidth_limit || 0;

  let config = `# FRP Client Configuration for ${user.email}
# Generated by FRP Panel

serverAddr = "${serverAddr}"
serverPort = ${serverPort}
auth.token = "${token}"

log.to = "./frpc.log"
log.level = "info"
log.maxDays = 3
`;

  ports.forEach((p) => {
    const proxyName = `${user.email.split('@')[0]}-${p.protocol}-${p.port}`;
    config += `
[[proxies]]
name = "${proxyName}"
type = "${p.protocol}"
localIP = "${p.local_ip || '127.0.0.1'}"
localPort = ${p.local_port || p.port}
remotePort = ${p.port}
`;
    // 添加限速配置
    if (bandwidthLimit > 0) {
      config += `transport.bandwidthLimit = "${bandwidthLimit}KB"
transport.bandwidthLimitMode = "client"
`;
    }
  });

  return config.trim();
}
